// AUTH DB
let userDB={
     userId:"",
     username:"",
     passwordHash:"",
     accountCreatedTime:1703743914914,
     profilePhotoURL:"",
     profilePhotoThumbURL:"",
     description:"",
     postsCount:10,
     posts:[
          {
               postID:"",
               postThumbURL:"",
               mediaCount:3,
               media:[
                    {
                         mediaType:"video/mp4",
                         mediaThumbURL:"",
                         mediaURL:""
                    },{},{}
               ],
               postedTime:1703743914914,
               caption:"",
               location:"",
               flags:{
                    hideLikes:false,
                    hideComments:true,
                    disableComments:false
               },
               likes:7,
               likedBy:[ userId_1, userId_2, userId_3 ],
               commentsCount:5,
               comments:[
                    {
                         commentor_userId:"",
                         comment:"",
                         likes:3,
                         likedBy: [ userId_1, userId_2, userId_3 ]
                    },
                    //...
               ],
          },{},{}
          //...
     ],
     followers:[
          {
               userId:userId_1,
               photoThumbURL:""
          },
          {
               userId:userId_2,
               photoThumbURL:""
          },
          {
               userId:userId_3,
               photoThumbURL:""
          },
     ],
     following:[
          {
               userId:userId_1,
               photoThumbURL:""
          },
          {
               userId:userId_2,
               photoThumbURL:""
          },
          {
               userId:userId_3,
               photoThumbURL:""
          },
     ],
     savedPosts:[
          postID_1, postID_2
     ],
     notifications:[
          {
               notificationID:"",
               content:"",
               notificationThumbURL:"",
               createdTime:"",
               linkToAction:""
          },
          //...
     ],

}